"""Diagnostics collected by `masora check`."""

from __future__ import annotations

from dataclasses import dataclass

ERROR = "error"
WARNING = "warning"

E_FRONTMATTER = "E-FRONTMATTER"
E_YAML = "E-YAML"
E_CANON_FLOW = "E-CANON-FLOW"
E_CANON_DUPKEY = "E-CANON-DUPKEY"
E_CANON_ALIAS = "E-CANON-ALIAS"
E_CANON_TAG = "E-CANON-TAG"
E_CANON_QUOTE = "E-CANON-QUOTE"
E_CANON_KEY = "E-CANON-KEY"
E_ULID = "E-ULID"
E_FILENAME = "E-FILENAME"
E_SCHEMA = "E-SCHEMA"
E_VERSION = "E-VERSION"
E_TIMESTAMP = "E-TIMESTAMP"
E_ANCHOR = "E-ANCHOR"
E_PROOFQUERY = "E-PROOFQUERY"
E_SUMMARY = "E-SUMMARY"
E_PROVENANCE = "E-PROVENANCE"
E_DUP_ID = "E-DUP-ID"
E_TOMBSTONED = "E-TOMBSTONED"
E_TOMBSTONE_SHAPE = "E-TOMBSTONE-SHAPE"
E_CYCLE = "E-CYCLE"
E_TARGET_KIND = "E-TARGET-KIND"
E_LINEAGE = "E-LINEAGE"
E_REWRITE = "E-REWRITE"
E_GC_UNAVAILABLE = "E-GC-UNAVAILABLE"
E_GC_ULID = "E-GC-ULID"
E_GC_UNKNOWN = "E-GC-UNKNOWN"
E_GC_CHECK = "E-GC-CHECK"
E_FOUNDER = "E-FOUNDER"
E_TOMBSTONE_SHRINK = "E-TOMBSTONE-SHRINK"
E_GIT = "E-GIT"
E_NO_ORIGIN = "E-NO-ORIGIN"
E_MERGE_BASE = "E-MERGE-BASE"
E_SETUP_ARG = "E-SETUP-ARG"
E_SETUP_CLONE = "E-SETUP-CLONE"
E_SETUP_NO_TOML = "E-SETUP-NO-TOML"
E_SETUP_SCHEMA = "E-SETUP-SCHEMA"
E_SETUP_CONFIG = "E-SETUP-CONFIG"
E_SETUP_WRITE = "E-SETUP-WRITE"
E_SETUP_DUPLICATE = "E-SETUP-DUPLICATE"
E_IDX_REPO = "E-IDX-REPO"
E_IDX_WRITE = "E-IDX-WRITE"
E_IDX_CORRUPT = "E-IDX-CORRUPT"
E_IDX_NOINDEX = "E-IDX-NOINDEX"
E_IDX_QUERY = "E-IDX-QUERY"
E_MCP_ARGS = "E-MCP-ARGS"
E_MCP_NO_BASE = "E-MCP-NO-BASE"
E_MCP_GRAPH = "E-MCP-GRAPH"
E_MCP_UNKNOWN_ID = "E-MCP-UNKNOWN-ID"
E_MCP_ANCHOR = "E-MCP-ANCHOR"
E_MCP_DRIFT = "E-MCP-DRIFT"
E_FACTS_NO_BASE = "E-FACTS-NO-BASE"
E_FACTS_NOINDEX = "E-FACTS-NOINDEX"
W_DANGLING = "W-DANGLING"
W_SKEW = "W-SKEW"
W_FOUNDER = "W-FOUNDER"
W_GC_ACTIVE = "W-GC-ACTIVE"
W_REPLAY = "W-REPLAY"
W_IDX_CORRUPT = "W-IDX-CORRUPT"
W_IDX_STALE = "W-IDX-STALE"
W_IDX_GRAPH = "W-IDX-GRAPH"
W_MCP_PROTO = "W-MCP-PROTO"


@dataclass(frozen=True)
class Diag:
    severity: str
    code: str
    message: str
    path: str | None = None

    def render(self) -> str:
        where = f" {self.path}" if self.path else ""
        return f"{self.severity} {self.code}:{where} {self.message}"


class CheckFailure(Exception):
    def __init__(self, diag: Diag):
        super().__init__(diag.message)
        self.diag = diag
